common: &default_settings
  api_key: "91f455bf0d3448173043fd334cbec463-us7"
  subscriber_list: "61d4987e01"

development:
  <<: *default_settings
test:
  <<: *default_settings
demo:
  <<: *default_settings
staging:
  <<: *default_settings

production:
  api_key: "91f455bf0d3448173043fd334cbec463-us7"
  subscriber_list: "61d4987e01"